### ISSUE TITLE
After you modify the time range, you can still create a schedule that is outside the scope

### ISSUE THREAD

**Issue by cx4** [nhn/tui.calendar#969] opened 2021-12-30 05:50 UTC
if i modify the time range in 
``` this.options = util.extend(
        {
            viewName: name,
            renderStartDate: '',
            renderEndDate: '',
            hourStart: 8,
            hourEnd: 18,
            timezones: options.timezones,
            isReadOnly: options.isReadOnly,
            showTimezoneCollapseButton: false
        },
        options.week
    );```
but can still create a schedule out the time range.

**Comment by adhrinae** [comment] 2021-12-30 08:31
@cx4 Please describe the issue in detail following the issue template.

Any example code reproducing the problem would be helpful.

Closing the issue since lack of information.

**Closed by adhrinae** 2021-12-30 08:31 UTC
Labels: Enhancement, Need Discussion
