### ISSUE TITLE
I want to achieve:in monthView,when i drag one schedule,original schedule not move and copy a new scheule  to target date.

### ISSUE THREAD

**Issue by bigcatLiu** [nhn/tui.calendar#1048] opened 2022-03-21 03:27 UTC
in move.js
![image](https://user-images.githubusercontent.com/20273421/159201310-0a436869-6e8f-4f03-996b-164ede0c996f.png)
![image](https://user-images.githubusercontent.com/20273421/159201391-700d3282-aa7d-4983-b6d5-6bf5b90509b1.png)
I made these changes,but it didn't trigger 'beforeCreateSchedule' function! 
Please tell me what's wrong with me! thanks!

**Comment by adhrinae** [comment] 2022-03-21 05:17
@bigcatLiu 

Let's make it simple. You actually don't need to modify the source code.
When you drag and drop a certain schedule, the `beforeUpdateSchedule` event fires only. Nothing else happens. ([Though the full application example in the repository already defined every behavior of the calendar.](https://github.com/nhn/tui.calendar/blob/master/examples/example00-basic.html))

So all you need to do is copy properties from the original schedule and merge it to the next start/end date, then call the `createSchedules` method. Suppose you need to duplicate the schedule when the user is pressing the `Alt/Option` key while dragging.

```js
let isOptKeyPressed = false;

document.addEventListener('keydown', (e) => {
    if (e.key === 'Alt') {
        isOptKeyPressed = true;
    }
});

document.addEventListener('keyup', (e) => {
    isOptKeyPressed = false;
});

const cal = new tui.Calendar('#calendar', {
    defaultView: 'month',
});

cal.on('beforeUpdateSchedule', (e) => {
    if (isOptKeyPressed) {
        const duplicatedSchedule = { ...e.schedule, ...e.changes };
        cal.createSchedules([duplicatedSchedule]);
    }
});
```

**Comment by bigcatLiu** [comment] 2022-03-21 07:05
Thank you very much!!
The problem is solved!
I'm so embarrassed！

**Comment by adhrinae** [comment] 2022-03-21 07:12
Closing the issue is resolved.

**Closed by adhrinae** 2022-03-21 07:12 UTC
Labels: Question, Answered
