### ISSUE TITLE
Custom view - inline

### ISSUE THREAD

**Issue by AurelienPillevesse** [nhn/tui.calendar#1288] opened 2022-09-21 17:04 UTC
Hello everyone,

I just starting to watch this repository, is it possible to have an inline view or not ?

I explain my idea : it would be a line per user (with a list of selected users)
At the left, it would be the user name and at the right , it would be days (monday/tuesday/thursday/...) on the same line visible by scrolling the block to the right.

If anyone has an answer, thanks!

Best regards,

**Comment by adhrinae** [comment] 2022-09-22 00:31
It's a duplicate of many issues such as #567, and we don't have a plan to implement this feature.

Somehow, as a workaround, I remember that someone had created multiple instances for each user(row). but I don't remember which it is 😞

**Comment by adhrinae** [comment] 2022-09-22 00:31
Closing since it's a duplicated issue.

**Closed by adhrinae** 2022-09-22 00:31 UTC
Labels: Duplicate
