### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by cfoellmann** [nhn/tui.calendar#1029] opened 2022-02-24 06:57 UTC
Is there any way to translate the UI? Buttons and the small number of strings.

Or is there a way to change these strings "manually"? Couldnt find any way how

**Comment by adhrinae** [comment] 2022-02-25 01:25
@cfoellmann 
Hi. I think this issue is a duplicate of #90.
We don't have a plan to support i18n yet, however, you can leverage some options and templates.

Please check the issue I've connected to. Closing.

**Closed by adhrinae** 2022-02-25 01:25 UTC
Labels: Enhancement, Need Discussion
