### ISSUE TITLE
Question with popupDetailBody in month view

### ISSUE THREAD

**Issue by samuel-xiangpeng** [nhn/tui.calendar#1290] opened 2022-09-26 14:32 UTC
## Version
v2.1.3

## Test Environment
OS,
chrome

## Current Behavior
[https://stackblitz.com/edit/react-xktdsp?file=src/App.js](https://stackblitz.com/edit/react-xktdsp?file=src/App.js)

```js
import React from 'react';
import Calendar from '@toast-ui/react-calendar';

import '@toast-ui/calendar/dist/toastui-calendar.min.css';
import './style.css';

export default function App() {
  const events = [
    {
      id: 'test_event',
      calendarId: 'PROCESS',
      title: 'TEST EVENT',
      start: '2022-09-02T09:00:00',
      end: '2022-09-04T10:00:00',
      isVisible: true,
      isAllday: true,
    },
    {
      id: 'test_event_1',
      calendarId: 'CLOSED',
      title: 'TEST EVENT_1',
      start: '2022-09-22T09:00:00',
      end: '2022-09-23T10:00:00',
      isVisible: true,
      isAllday: true,
    },
    {
      id: 'test_event',
      calendarId: 'DONE',
      title: 'TEST EVENT',
      start: '2022-09-22T09:00:00',
      end: '2022-09-23T10:00:00',
      isVisible: true,
      isAllday: true,
    },
    {
      id: 'test_event',
      calendarId: 'DONE',
      title: 'TEST EVENT',
      start: '2022-09-22T09:00:00',
      end: '2022-09-23T10:00:00',
      isVisible: true,
      isAllday: true,
    },
    {
      id: 'test_event',
      calendarId: 'DONE',
      title: 'TEST EVENT',
      start: '2022-09-22T09:00:00',
      end: '2022-09-23T10:00:00',
      isVisible: true,
      isAllday: true,
    },
  ];
  return (
    <div>
      <Calendar
        height="100vh"
        view={'month'}
        useDetailPopup={true}
        events={events}
        tempalte={{
          popupDetailBody: function (schedule) {
            return `<div id="tui-do-calendar-detail">详情</div>`;
          },
        }}
      />
    </div>
  );
}

```

## Expected Behavior
I want use popupDetailBody to customize render popup, i want  to know how to use this api correctlly.

**Comment by adhrinae** [comment] 2022-09-26 23:14
Duplicate of #1279.

1. You misspelled the prop's name as `tempalte`, not `template`.
2. Check out the discussion above for more information.

**Comment by adhrinae** [comment] 2022-09-26 23:15
Closing since the question is answered.

**Closed by adhrinae** 2022-09-26 23:15 UTC
Labels: Duplicate, Question, Answered

**Comment by samuel-xiangpeng** [comment] 2022-09-27 00:47
I have modified it but it still does not take effect. Can you help me see?

**Comment by samuel-xiangpeng** [comment] 2022-09-27 00:48
![image](https://user-images.githubusercontent.com/81249809/192406013-74ac96d3-5620-4361-b1fb-483ba229c4d4.png)

**Comment by samuel-xiangpeng** [comment] 2022-09-27 01:00
Thanks， I know how to do.
