### ISSUE TITLE
Disable then enable useDetailPopup creates an error

### ISSUE THREAD

**Issue by PSVcode** [nhn/tui.calendar#699] opened 2020-09-19 08:17 UTC
## Version

/*!
 * TOAST UI Calendar
 * @version 1.12.13 | Tue Apr 28 2020
 * @author NHN FE Development Lab <dl_javascript@nhn.com>
 * @license MIT
 */

## Development Environment

OSX Mojave 10.14.6 / Chrome Version 85.0.4183.102 (Build officiel) (64 bits)

## Current Behavior

If I disable detail popups, it works. But it crashes when I try to enable them again. Maybe this is not the right way to do it...
```js
// Write example code
cal.setOptions({useDetailPopup:true});
cal.setOptions({useDetailPopup:false});
cal.setOptions({useDetailPopup:true}); // crash
```
The problem also arises if you type this sample code in the console at https://nhn.github.io/tui.calendar/latest/tutorial-example00-basic. Here is the reported error :

weekView.js:329 Uncaught TypeError: Cannot read property 'off' of undefined
    at Week.weekView._beforeDestroy (weekView.js:329)
    at Week../src/js/view/view.js.View._destroy (view.js:153)
    at Week../src/js/view/view.js.View.destroy (view.js:174)
    at Collection.<anonymous> (layout.js:52)
    at o (tui-code-snippet.min.js:7)
    at Collection../src/js/common/collection.js.Collection.each (collection.js:425)
    at Layout../src/js/view/layout.js.Layout.clear (layout.js:51)
    at Calendar../src/js/factory/calendar.js.Calendar.changeView (calendar.js:1576)
    at Calendar../src/js/factory/calendar.js.Calendar.setOptions (calendar.js:1715)
    at <anonymous>:1:5

## Expected Behavior

Enable again the datail popups.

**Comment by jungeun-cho** [comment] 2020-09-24 01:31
I reproduced. This is a bug and will be fixed.

**Comment by WillTA5** [comment] 2021-12-08 15:10
I'm having this issue too, wondering if there's any news?

**Comment by adhrinae** [comment] 2021-12-09 03:40
@WillTA5 
Sorry, There's no progress about this issue yet.
I'll investigate the cause and try to fix it. Possibly before the end of this year if I can.

**Comment by Raketten1963** [comment] 2022-01-28 07:49
I am having this issue too. Wondering, is there any news?

**Comment by adhrinae** [comment] 2022-02-03 00:36
@Raketten1963
I forgot this issue while fixing other issues. My bad.
I need to investigate the problem first, then I'll plan the release of the fixed version.

**Closed** 2022-02-17 05:49 UTC
Labels: Bug, To Do

**Comment by adhrinae** [comment] 2022-02-17 06:17
@WillTA5 @Raketten1963 @PSVcode 

The issue is resolved. Please use [the latest version(v1.15.3)](https://github.com/nhn/tui.calendar/releases/tag/v1.15.3).
