### ISSUE TITLE
No guide element when trying to edit a newly created Schedule in the calendar

### ISSUE THREAD

**Issue by klimentpetkov** [nhn/tui.calendar#952] opened 2021-12-07 15:23 UTC
## Describe the bug
No guide element when trying to edit a newly created Schedule in the calendar

## To Reproduce
1. Click on a day of the calendar
2. Create a new schedule
3. Save the schedule
4. Click on the same schedule to edit it -> A popup appears
5. Click on the Edit button of the appeared popup
6. See the error:
tui-calendar.js?6c33:22157 Uncaught TypeError: Cannot read property 'guideElement' of undefined
    at ScheduleCreationPopup../src/js/view/popup/scheduleCreationPopup.js.ScheduleCreationPopup._getGuideElements (SfbR:22152)
    at ScheduleCreationPopup../src/js/view/popup/scheduleCreationPopup.js.ScheduleCreationPopup.render (SfbR:22044)
    at onShowEditPopup (SfbR:12859)
    at ScheduleDetailPopup.CustomEvents.invoke (+hs0:3225)
    at ScheduleDetailPopup.CustomEvents.fire (+hs0:3180)
    at ScheduleDetailPopup../src/js/view/popup/scheduleDetailPopup.js.ScheduleDetailPopup._onClickEditSchedule (SfbR:22629)
    at ScheduleDetailPopup../src/js/view/popup/scheduleDetailPopup.js.ScheduleDetailPopup._onClick (SfbR:22616)
    at HTMLDivElement.handler (SfbR:5410)

## Expected behavior
Open a dialog to edit the schedule

## Desktop (please complete the following information):
 - OS: Linux
 - Browser Chrome

**Comment by adhrinae** [comment] 2021-12-08 00:10
@klimentpetkov

Could you give some example code reproducing the error? Jsfiddle, Codesandbox, etc.
It looks ok on my side. Maybe it might be related to your option when you create the calendar instance. or other codes.

**Comment by adhrinae** [comment] 2022-01-05 06:04
Closing the issue due to unresponsiveness.

**Closed by adhrinae** 2022-01-05 06:04 UTC
Labels: Bug
