### ISSUE TITLE
calendar date disappear when i have multiple calendar

### ISSUE THREAD

**Issue by andreameneguzzoinfol** [nhn/tui.calendar#1043] opened 2022-03-14 17:17 UTC
Goodmorning All,
i have found this issue.
i have multiple calendar on my web page called cal1,cal2,cal3,cal4
i have found that when i open a new schedule on cal 2 the date of start date and date appear
if i click then on new schedule on cal3 the date disappear,
if i click anyway on new schedule of cal1 the date appear.
it's like that everytime i click on calendar the index of the maximum calendar is -1
![immagine](https://user-images.githubusercontent.com/24794417/158225564-43b65963-765b-4bb6-90ba-4b6f2e308522.png)

**Comment by adhrinae** [comment] 2022-03-15 00:15
Hi, It's really hard to understand what the problem is.

Did you mean that you created multiple calendar instances? or something else?
And the screenshot looks irrelevant to the issue.

Please upload any example code which can reproduce the problem. (GitHub Repo, Codesandbox, Glitch, etc.)

**Comment by andreameneguzzoinfol** [comment] 2022-03-15 09:01
yes i have created multiple istances of calendar



     var cal = new tui.Calendar('#calendar1', {
            defaultView: 'month', // set 'month'
            useCreationPopup: true,
            useDetailPopup: true,
            calendars: CalendarList,
            template: {
                milestone: function(model) {
                    return '<span class="calendar-font-icon ic-milestone-b"></span> <span style="background-color: ' + model.bgColor + '">' + model.title + model.body + '</span>';
                }
            },
            month: {
                workweek: true // show only 5 days except for weekend
            }
        });
    
     var cal2 = new tui.Calendar('#calendar1', {
        defaultView: 'month', // set 'month'
        useCreationPopup: true,
        useDetailPopup: true,
        calendars: CalendarList,
        template: {
            milestone: function(model) {
                return '<span class="calendar-font-icon ic-milestone-b"></span> <span style="background-color: ' + model.bgColor + '">' + model.title + model.body + '</span>';
            }
        },
        month: {
            workweek: true // show only 5 days except for weekend
        }
    });

**Comment by adhrinae** [comment] 2022-03-16 00:29
I got the point. You want multiple calendar instances with the default schedule creation popup.
The default popup doesn't support multiple calendar instances at the moment. So you can only see the date picker on the first calendar instance you've interacted.
You have to create your own popup for your use case.

By the way, Creating calendar instances with the same container element (`#calendar1` in your example code) is not a good idea. Please use different containers by calendars.

**Comment by adhrinae** [comment] 2022-03-16 00:30
Closing the issue since it's not a bug and answered.

**Closed by adhrinae** 2022-03-16 00:30 UTC
Labels: Question, Answered, Known Issue

**Comment by andreameneguzzoinfol** [comment] 2022-03-16 07:34
Hello,i copied the wrong code:

the correct is:



      var cal = new tui.Calendar('#calendar1', {
              defaultView: 'month', // set 'month'
              useCreationPopup: true,
              useDetailPopup: true,
              calendars: CalendarList,
              template: {
                  milestone: function(model) {
                      return '<span class="calendar-font-icon ic-milestone-b"></span> <span style="background-color: ' + model.bgColor + '">' + model.title + model.body + '</span>';
                  }
              },
              month: {
                  workweek: true // show only 5 days except for weekend
              }
          });
      
       var cal2 = new tui.Calendar('#calendar2', {
          defaultView: 'month', // set 'month'
          useCreationPopup: true,
          useDetailPopup: true,
          calendars: CalendarList,
          template: {
              milestone: function(model) {
                  return '<span class="calendar-font-icon ic-milestone-b"></span> <span style="background-color: ' + model.bgColor + '">' + model.title + model.body + '</span>';
              }
          },
          month: {
              workweek: true // show only 5 days except for weekend
          }
      });


i know that is not supported but it seems to works except to this case:
i click on the event1 on the calendar2 and the popup appear with date and time picker.
then i click on the event2 on the calendar 2 and the popup appear with date and time picker.
then i click on the event3 on the calendar 1 and the popup appear with date and time picker.
then i click on the event4 on the calendar 2 and the popup appear **WITHOUT** date and time picker.

it seems that when you click on calendar -1 the maximum calendar that works is that and the calendar -2 -3 ...

**Comment by adhrinae** [comment] 2022-03-16 23:02
@andreameneguzzoinfol 

You might feel the things like that. but it's not.

For more information, when the datetime picker is mounted, it's looking for the element following a fixed selector.

https://github.com/nhn/tui.calendar/blob/0a56f7ddfeb716c440eebc78a61d6287b9e2bb21/src/js/view/popup/scheduleCreationPopup.js#L627-L636

But every instance has those elements with the same name of ids. so the datetime picker cannot find the right position which they should be mounted.
