### ISSUE TITLE
"beforeUpdateSchedule" and all events related with update events, always return zDate nulls

### ISSUE THREAD

**Issue by blah-iseeyou** [nhn/tui.calendar#1325] opened 2022-12-05 19:15 UTC
I used the V2 and in the triggered events that are related to update an event, always return the zDates (star and end) like nulls. 

This happens a lot, doest mater if I change the ID, the title, o whatever, always return the dats like null.

**Comment by adhrinae** [comment] 2022-12-05 22:55
Looks like you're trying to set events using v1's namespaces.

It should be `beforeUpdateEvent`.

Duplicate of [#1262](https://github.com/nhn/tui.calendar/issues/1262#issuecomment-1227816561), #1275.

**Closed by adhrinae** 2022-12-05 22:55 UTC
Labels: Duplicate, 2.0
