### ISSUE TITLE
How to deactivate status dropdown from the pre-built Edit-Modal

### ISSUE THREAD

**Issue by FelixBrgn** [nhn/tui.calendar#900] opened 2021-09-11 14:33 UTC
## Summary
I'm working on an angular project and I want to remove the "State" dropdown menu from the prebuilt one. Tried removing the functions that render it from the template object from which I create the calendar.

**Comment by adhrinae** [comment] 2021-09-13 01:14
@FelixBrgn 

You need to fork the source code and edit & bundle it on your own.
Otherwise, you need to implement your own modal.

Duplicate of #812, #884

**Closed by adhrinae** 2021-09-13 01:14 UTC
Labels: Question
