### ISSUE TITLE
Is it possible to set interval minutes in TUI Calendar (Weekly mode)

### ISSUE THREAD

**Issue by RentaYustikaDamanik05** [nhn/tui.calendar#839] opened 2021-06-18 06:30 UTC
## Current Behavior

```js
// Write example code
this.calendar = new tui.Calendar('#weekly-schedule-salesman', {
            defaultView: 'week', // weekly view option
            theme: WEEKLY_CUSTOM_THEME,
            taskView: false,
            scheduleView: ['time'],
            week: {
                daynames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                startDayOfWeek: 1,
                hourStart: 7,
                // narrowWeekend: true,
                goingDuration : 30,
            }
});
```

## Expected Behavior

For now, my tui calendar show data in 1 hour interval. I want to make my calendar in 30 minutes interval. Is it possible? If yes, can anyone help me how to solve it? Thank you.

**Comment by adhrinae** [comment] 2021-06-18 09:21
We don't support a custom duration feature yet.
It's a duplicate of #373

**Comment by RentaYustikaDamanik05** [comment] 2021-06-18 10:13
Thank you for the answer.

**Closed** 2021-06-21 01:21 UTC
Labels: Duplicate
