### ISSUE TITLE
clickSchedule/beforeCreateSchedule/beforeUpdateSchedule events do not fire in v2.1.3

### ISSUE THREAD

**Issue by Avinodh** [nhn/tui.calendar#1345] opened 2023-01-09 00:44 UTC
## Version
2.1.3

## Test Environment
Google Chrome, Microsoft Edge

## Current Behavior
Based on the suggestions in this past issue: https://github.com/nhn/tui.calendar/issues/812 , I am trying display a custom pop for event creation:

```
        .  .  .
        const options = {
            defaultView: 'week',
            usageStatistics: false,
            useFormPopup: false,
            useDetailPopup: false,
            useCreationPopup: false,
            timezone: {
                zones: [
                {
                    timezoneName: 'America/Los_Angeles',
                    displayLabel: 'Los Angeles',
                },
                ],
            },
            calendars: [
                {
                id: 'calendar1',
                name: 'Personal',
                },
            ],
            week: {
                taskView: false,
            },
        };
        
        const Calendar = tui.Calendar;
        this.calendarInstance = new Calendar(container, options);
        
        // Event handlers
        //
        this.calendarInstance.on({
          'clickSchedule': function(e) {
              console.log('clickSchedule', e);
          },
          'beforeCreateSchedule': function(e) {
              console.log('beforeCreateSchedule', e);
          },
          'beforeUpdateSchedule': function(e) {
              console.log('beforeUpdateSchedule', e);
          },
          'beforeDeleteSchedule': function(e) {
              console.log('beforeDeleteSchedule', e);
          }
        });

```

However, when I  click the calendar to create a new event, none of these events fire/nothing is printed in the console:
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/5704154/211226942-4cdf966a-e630-4af1-a627-f8954c364bed.png">

**Note:** If i  re-enable  `useFormPopup: true`, `useDetailPopup: true`, `useCreationPopup: true`, I  am able to use other events such as `beforeCreateEvent`, `beforeUpdateEvent`, `beforeDeleteEvent`, etc. However, these above events still do not fire.

## Expected Behavior
Are these events not supported any longer? How can I  display custom pop-ups in the current version? 
Thank you!

**Comment by adhrinae** [comment] 2023-01-09 01:16
It's a duplicate of #1262.

https://github.com/nhn/tui.calendar/issues/1262#issuecomment-1227816561

Please note that we don't use the term 'Schedule' anymore. You've read an issue about the previous version but same strategy is needed to create custom popups.

https://github.com/nhn/tui.calendar/blob/main/docs/en/guide/migration-guide-v2.md#change-term-from-schedule-to-event

**Closed** 2023-01-09 01:16 UTC
Labels: Duplicate, 2.0
