### ISSUE TITLE
hide resize icon when isReadOnly=true is set for calendar widget

### ISSUE THREAD

**Issue by mariusa** [nhn/tui.calendar#470] opened 2019-11-28 22:54 UTC
Hi,

When one sets isReadOnly=true for each schedule, the resize icon is hidden. 

However, when isReadOnly=true is set for calendar widget, the resize icon still shows (resizing is disabled though).
```
<calendar
                        ref="calendar"
                        :calendars="calendars"
                        :schedules="schedules"
                        style="height: auto;"
                        :isReadOnly="true"
                    />
```

Please hide resize icon when isReadOnly=true is set for calendar widget. Thanks!

Maybe related: https://github.com/nhn/tui.calendar/commit/ca87dd5bc134a21df01a84e057da4022e0eed8ee

**Comment by jungeun-cho** [comment] 2019-11-29 02:55
@mariusa 
The calendar option is set so that all schedules currently displayed in the calendar are shown as `readOnly` and the resize button is also hidden.

I will schedule it. I think it will be released in the next patch version.

**Comment by jungeun-cho** [comment] 2020-03-23 07:34
@mariusa 

I'm sorry.
There was a problem with my test.
The issue is still being reproduced.

It will be revised and released again.

**Closed** 2020-04-17 01:23 UTC
Labels: Bug, Category: Options, To Do
