### ISSUE TITLE
The 2 week/3 week/ month view does not fit the container provided to it without a scrollbar.

### ISSUE THREAD

**Issue by sriramramaswami** [nhn/tui.calendar#1209] opened 2022-07-13 17:57 UTC
## Version
1.15.3

## Test Environment
Chrome 103, Windows 10, Angular 12.2.16

## Current Behavior
I am unable to get the 2/3 week/month view to render as per the container size provided. It seems to take a minimum height no matter what, I have created a stackblitz to demonstrate the issue. I have set the container height to 350px. But the month view does not seem to shrink to accommodate it. I need to provide a scrollbar to see the entire content which is not an acceptable workaround at the moment.

Stackblitz: https://angular-gr7nju.stackblitz.io

```js
// Write example code
this.calendar = new Calendar('#calendar', {
      defaultView: 'month',
      taskView: false,
      disableClick: true,
      disableDblClick: true,
      useCreationPopup: false,
      useDetailPopup: false,
      usageStatistics: false,
      month: {
        narrowWeekend: true,
        startDayOfWeek: 0,
      },
      week: {
        narrowWeekend: true,
        startDayOfWeek: 0,
      },
      calendars: [
        {
          id: '1',
          name: 'calendar',
        },
      ],
    });
```

## Expected Behavior
1. The calendar should be able to occupy the size of the container provided to it without a scrollbar.

**Comment by adhrinae** [comment] 2022-07-13 23:51
It looks duplicate of #842. I wrote a possible workaround in #842, so please refer to that.

**Closed** 2022-09-28 04:03 UTC
Labels: Question, Answered, Known Issue
