### ISSUE TITLE
onClickSchedule and schedule-related event is not working

### ISSUE THREAD

**Issue by wlcharlie** [nhn/tui.calendar#1275] opened 2022-09-07 07:20 UTC
## Version

- toast-ui/react-calendar: 2.1.3
- next: 12.2.5
- react: 18.2.0
- react-dom: 18.2.0

## Test Environment
Chrome, Window

and Here: https://codesandbox.io/s/headless-resonance-9iqql0?file=/Calendar/index.js:1378-1391

## Current Behavior
I was trying to add event `onClickSchedule` by using `Calendar.on(...)`, and seemed not firing it.

I create a demo on codesandbox and also show how i use it currently. 

https://codesandbox.io/s/headless-resonance-9iqql0?file=/Calendar/index.js:1378-1391

the reference i was looking on:
https://github.com/nhn/tui.calendar/issues/124
https://github.com/nhn/tui.calendar/blob/v1/docs/getting-started.md#customize-popups

the demo that worked (found on Codepen):
https://codepen.io/001123/pen/JZRrMb

## Expected Behavior
Expected it work >__<

Did I miss any step?

**Comment by adhrinae** [comment] 2022-09-07 07:48
It's a duplicate of #1262.

Please see [this comment](https://github.com/nhn/tui.calendar/issues/1262#issuecomment-1227816561).

**Closed by adhrinae** 2022-09-07 07:48 UTC
Labels: Duplicate

**Comment by wlcharlie** [comment] 2022-09-07 09:32
@adhrinae WOW! Thanks for quick replying. Appreciated!

But I am still wondering at `clickSchedule` , is not avaliable on React currently?
Since i was also trying to make blue container behave like this way: 
(which is kind of stay on it until i refresh whole thing)
https://github.com/nhn/tui.calendar/issues/124#issuecomment-391655721
![40477948-b8c74b36-5f82-11e8-8ffe-3b084536fb26](https://user-images.githubusercontent.com/77925413/188844475-29c86994-7e00-4e36-a3f7-46ce2a3222b1.gif)

**Comment by adhrinae** [comment] 2022-09-07 23:19
@wlcharlie 

First, the `clickSchedule` prop should be the `onClickEvent`. Check out related comments on the issue I mentioned before.

And about clearing selection, refer to [this](https://github.com/nhn/tui.calendar/issues/1213#issuecomment-1186650116) issue.

**Comment by wlcharlie** [comment] 2022-09-08 02:01
@adhrinae Hey!

Finally figured it out by combine it by this:
```
onSelectDateTime={e => Calandar.getInstance().clearGridSelections()}
```

Thanks for paitently reply 😭 ❤️
